"""Deterministic, rule-based narrative generation over the pipeline's own
structured output (a `StrategyCandidate` dict, a `RegimeResult`, a
`risk_engine.evaluate()` decision dict, the council's `AgentOpinion`s and
`ChiefIntelligenceThesis`).

This module runs strictly *after* `risk_engine.evaluate()` and
`council.synthesize()` have already produced their outputs — it restates
them in plain-language, broker-voice prose. It never re-derives a decision
(the same discipline `RiskOfficer` already follows: its opinion *is*
`risk_engine`'s decision, translated, never recomputed), never invents a
number that isn't already a field on its inputs, and never generates text
via an LLM — every sentence here is a fixed template over real data.

Per brief Section 24 ("do not treat AI text output as a market signal")
and this repo's non-goal of never promising profitability: every branch
below ends with a fixed disclaimer (`DISCLAIMER_EN`/`DISCLAIMER_ES`),
verbatim, including the REJECT branch. This is presentation of an existing
decision, not a new source of trading authority — nothing in this module
can place, size, or approve a trade.

**Language (`language: "en" | "es"`)**: both renders come from the exact
same inputs — `run_pipeline.py` calls this function twice per symbol, once
per language, against one pipeline run, never re-deriving anything.
`reason`/`finding` `detail` strings (e.g. `"position would be 5.00%, limit
is 3.00%"`) are machine-generated numeric diagnostics from risk_engine/the
agents and are **never translated** in either language — only the prose
sentence around them is. Regime/direction/stance enum values (e.g.
`BULLISH_TREND`, `SUPPORT`) are rendered as natural Spanish words inside
Spanish prose via the `_..._LABELS_ES` lookup tables below, but the
*stored/transmitted* values (the `regime`/`decision`/`finalStance` columns
this module's caller persists) are never translated — `language` only
changes prose, never the underlying structured data.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Literal

if TYPE_CHECKING:
    from regime_engine.classify import RegimeResult

    from ai_council.council import ChiefIntelligenceThesis
    from ai_council.opinion import AgentOpinion

Language = Literal["en", "es"]

DISCLAIMER_EN = (
    "This note is generated by rule-based code, not a licensed financial advisor, "
    "and reflects a simulated paper-trading account (starting equity $100,000, "
    "placeholder risk limits) — not your real portfolio. It is for informational "
    "and educational purposes only, is not investment advice, and no real capital "
    "is at risk from anything described here. Nothing in this note places or "
    "authorizes a trade."
)

DISCLAIMER_ES = (
    "Esta nota es generada por código basado en reglas, no por un asesor "
    "financiero con licencia, y refleja una cuenta simulada de trading en papel "
    "(capital inicial de $100,000, límites de riesgo predeterminados) — no tu "
    "portafolio real. Es solo para fines informativos y educativos, no "
    "constituye asesoría de inversión, y ningún capital real está en riesgo por "
    "nada de lo descrito aquí. Nada en esta nota ejecuta ni autoriza una "
    "operación."
)


def _disclaimer(language: Language) -> str:
    return DISCLAIMER_ES if language == "es" else DISCLAIMER_EN


# Every code below is verified against risk_engine.engine and the four
# ai_council agents' actual source (grepped, not guessed). A code that
# isn't in this table still gets a readable fallback (see _plain_reason) —
# this table is polish, the fallback is the actual safety net.
_CODE_PHRASES_EN: dict[str, str] = {
    "OK": "no limits were binding",
    "KILL_SWITCH_ENGAGED": "the global kill switch is engaged",
    "CIRCUIT_BREAKER_ENGAGED": "a circuit breaker is engaged",
    "STALE_DATA": "the market data feeding this is stale",
    "LIQUIDITY_SPREAD_LIMIT": "the spread is wider than the allowed limit",
    "MAX_DAILY_LOSS": "the day's loss limit is already breached",
    "MAX_WEEKLY_LOSS": "the week's loss limit is already breached",
    "MAX_PORTFOLIO_DRAWDOWN": "portfolio drawdown is past its limit",
    "MAX_PORTFOLIO_VAR": "portfolio value-at-risk is past its limit",
    "MAX_POSITION": "the position size limit for this asset",
    "MAX_ASSET_EXPOSURE": "the asset exposure limit",
    "MAX_GROSS_EXPOSURE": "the gross exposure limit",
    "MAX_LEVERAGE": "the leverage limit",
    "MAX_NET_EXPOSURE": "the net exposure limit",
    "RISK_PER_TRADE_LIMIT": "the size requested risks more than the per-trade budget",
    "EDGE_TO_COST_RATIO": "the edge-to-cost math",
    "EDGE_DOES_NOT_COVER_COSTS": "the edge doesn't clear costs by enough",
    "INVALID_COST_BASIS": "the cost basis on this candidate doesn't check out",
    "LOW_REGIME_CONFIDENCE": "the regime read itself isn't very confident",
    "WEAK_SIGNAL_STRENGTH": "the signal strength is weak",
    "THIN_EDGE_MARGIN": "the edge over costs looks thin",
    "LOW_HISTORICAL_WIN_RATE": "the historical win rate on this setup is low",
    "REGIME_MISMATCH": "this candidate was built against a regime that's since changed",
    "MISSING_STRATEGY_ID": "the candidate is missing its strategy identifier",
    "INCONSISTENT_STOP_TARGET_ORDERING": (
        "the stop/target prices aren't ordered correctly for the stated direction"
    ),
}

_CODE_PHRASES_ES: dict[str, str] = {
    "OK": "no se superó ningún límite",
    "KILL_SWITCH_ENGAGED": "el interruptor de emergencia global está activado",
    "CIRCUIT_BREAKER_ENGAGED": "un disyuntor de circuito está activado",
    "STALE_DATA": "los datos de mercado que alimentan esto están desactualizados",
    "LIQUIDITY_SPREAD_LIMIT": "el spread es más amplio que el límite permitido",
    "MAX_DAILY_LOSS": "el límite de pérdida diaria ya se superó",
    "MAX_WEEKLY_LOSS": "el límite de pérdida semanal ya se superó",
    "MAX_PORTFOLIO_DRAWDOWN": "el drawdown del portafolio superó su límite",
    "MAX_PORTFOLIO_VAR": "el valor en riesgo (VaR) del portafolio superó su límite",
    "MAX_POSITION": "el límite de tamaño de posición para este activo",
    "MAX_ASSET_EXPOSURE": "el límite de exposición al activo",
    "MAX_GROSS_EXPOSURE": "el límite de exposición bruta",
    "MAX_LEVERAGE": "el límite de apalancamiento",
    "MAX_NET_EXPOSURE": "el límite de exposición neta",
    "RISK_PER_TRADE_LIMIT": "el tamaño solicitado arriesga más que el presupuesto por operación",
    "EDGE_TO_COST_RATIO": "la relación entre el margen esperado y el costo",
    "EDGE_DOES_NOT_COVER_COSTS": "el margen no cubre los costos por suficiente margen",
    "INVALID_COST_BASIS": "la base de costos de este candidato no cuadra",
    "LOW_REGIME_CONFIDENCE": "la lectura del régimen no es muy confiable",
    "WEAK_SIGNAL_STRENGTH": "la fuerza de la señal es débil",
    "THIN_EDGE_MARGIN": "el margen sobre los costos se ve escaso",
    "LOW_HISTORICAL_WIN_RATE": "la tasa de aciertos histórica de este planteamiento es baja",
    "REGIME_MISMATCH": "este candidato se construyó sobre un régimen que ya cambió",
    "MISSING_STRATEGY_ID": "al candidato le falta su identificador de estrategia",
    "INCONSISTENT_STOP_TARGET_ORDERING": (
        "el stop y el objetivo no están ordenados correctamente para la dirección indicada"
    ),
}

# Display-only lookup tables for Spanish prose. The underlying stored
# values (regime.label, candidate["direction"], thesis.final_stance) are
# never translated — only how they're phrased inside Spanish sentences.
_REGIME_LABELS_ES: dict[str, str] = {
    "BULLISH_TREND": "tendencia alcista",
    "BEARISH_TREND": "tendencia bajista",
    "SIDEWAYS": "lateral",
    "HIGH_VOLATILITY": "alta volatilidad",
    "LOW_VOLATILITY": "baja volatilidad",
    "ACCUMULATION": "acumulación",
    "DISTRIBUTION": "distribución",
    "STRESS_EVENT": "evento de estrés",
}

_DIRECTION_LABELS_ES: dict[str, str] = {
    "LONG": "en largo",
    "SHORT": "en corto",
    "NEUTRAL": "neutral",
}

_STANCE_LABELS_ES: dict[str, str] = {
    "SUPPORT": "a favor",
    "OPPOSE": "en contra",
    "NEUTRAL": "neutral",
    "VETO": "veto",
}


def _regime_es(label: str) -> str:
    return _REGIME_LABELS_ES.get(label, label)


def _direction_es(direction: str) -> str:
    return _DIRECTION_LABELS_ES.get(direction, direction)


def _stance_es(stance: str) -> str:
    return _STANCE_LABELS_ES.get(stance, stance)


def _confidence_word(confidence: float, language: Language) -> str:
    """Fixed, deterministic bucket — not per-call color commentary."""
    if language == "es":
        if confidence >= 0.75:
            return "razonablemente"
        if confidence >= 0.5:
            return "moderadamente"
        return "solo levemente"
    if confidence >= 0.75:
        return "reasonably"
    if confidence >= 0.5:
        return "moderately"
    return "only mildly"


def _plain_reason(reason: dict, language: Language) -> str:
    table = _CODE_PHRASES_ES if language == "es" else _CODE_PHRASES_EN
    prefix = table.get(reason["code"], reason["code"].replace("_", " ").lower())
    return f"{prefix} ({reason['detail']})"


def _no_candidate_paragraph(symbol: str, regime: RegimeResult, language: Language) -> str:
    if language == "es":
        return (
            f"{symbol} está actualmente en un régimen de {_regime_es(regime.label)} "
            f"(confianza del clasificador {regime.confidence:.0%}). Ninguna de las tres "
            f"estrategias que esta plataforma ejecuta hoy — seguimiento de tendencia, "
            f"reversión a la media o ruptura — está habilitada para operar en este "
            f"régimen, así que no se generó ningún candidato de operación. Esto no es "
            f"una señal para no hacer nada para siempre; solo significa que este "
            f"conjunto de reglas específico no tiene nada que decir sobre {symbol} en "
            f"este momento."
        )
    return (
        f"{symbol} is currently in a {regime.label} regime (classifier confidence "
        f"{regime.confidence:.0%}). None of the three strategies this platform runs "
        f"today — trend-following, mean-reversion, or breakout — are cleared to "
        f"operate in this regime, so no trade candidate was generated. That's not a "
        f"signal to do nothing forever; it just means this specific rule set has "
        f"nothing to say about {symbol} right now."
    )


def _multi_candidate_paragraph(candidate: dict, pool_size: int, language: Language) -> str:
    if language == "es":
        return (
            f"{pool_size} estrategias generaron candidatos para {candidate['symbol']} "
            f"en este régimen de {_regime_es(candidate['regime'])}; esta nota cubre "
            f"{candidate['strategyId']} (dirección {_direction_es(candidate['direction'])}), "
            f"seleccionado por tener el mayor margen esperado "
            f"({candidate['expectedEdge']:.4f}) entre ellos. Los demás no se discuten "
            f"aquí."
        )
    return (
        f"{pool_size} strategies generated candidates for {candidate['symbol']} in "
        f"this {candidate['regime']} regime; this note covers {candidate['strategyId']} "
        f"(direction {candidate['direction']}), selected because it had the highest "
        f"expected edge ({candidate['expectedEdge']:.4f}) among them. The others are "
        f"not discussed here."
    )


def _opening_paragraph(
    symbol: str, regime: RegimeResult, candidate: dict, language: Language
) -> str:
    if language == "es":
        return (
            f"{symbol} se está leyendo como un régimen de {_regime_es(regime.label)} "
            f"en este momento, y el clasificador está "
            f"{_confidence_word(regime.confidence, 'es')} seguro de esa lectura "
            f"({regime.confidence:.0%}). Con base en eso, la estrategia "
            f"{candidate['strategyId']} armó una idea "
            f"{_direction_es(candidate['direction'])} en un horizonte de "
            f"{candidate['horizon']}."
        )
    return (
        f"{symbol} is reading as a {regime.label} regime right now, and the "
        f"classifier is {_confidence_word(regime.confidence, 'en')} confident in that read "
        f"({regime.confidence:.0%}). On the back of that, the {candidate['strategyId']} "
        f"strategy put together a {candidate['direction']} idea on a "
        f"{candidate['horizon']} horizon."
    )


def _entry_stop_target_sentence(candidate: dict, language: Language) -> str:
    entry_price = candidate["entryLogic"].get("entryPrice")
    stop_price = candidate["stopLogic"].get("stopPrice")
    target_price = candidate["targetLogic"].get("targetPrice")

    if language == "es":
        parts = []
        if entry_price is not None:
            parts.append(f"entrada alrededor de {entry_price}")
        if stop_price is not None:
            parts.append(f"un stop en {stop_price}")
        if target_price is not None:
            parts.append(f"un objetivo en {target_price}")
        if not parts:
            return (
                "La estrategia no definió precios explícitos de entrada/stop/objetivo "
                "para este candidato."
            )
        return "El plan generado: " + ", ".join(parts) + "."

    parts = []
    if entry_price is not None:
        parts.append(f"entry around {entry_price}")
    if stop_price is not None:
        parts.append(f"a stop at {stop_price}")
    if target_price is not None:
        parts.append(f"a target at {target_price}")
    if not parts:
        return "The strategy didn't populate explicit entry/stop/target prices for this candidate."
    return "The plan as generated: " + ", ".join(parts) + "."


def _edge_cost_sentence(candidate: dict, language: Language) -> str:
    if language == "es":
        return (
            f"El margen esperado está modelado en {candidate['expectedEdge']:.4f} "
            f"contra costos estimados de {candidate['estimatedCosts']:.4f} — son "
            f"estimaciones propias de la estrategia, no un pronóstico de ganancias "
            f"validado."
        )
    return (
        f"Expected edge is modeled at {candidate['expectedEdge']:.4f} against "
        f"estimated costs of {candidate['estimatedCosts']:.4f} — these are the "
        f"strategy's own placeholder estimates, not a validated profit forecast."
    )


def _reject_paragraph(risk_decision: dict, language: Language) -> str:
    reasons = risk_decision["reasons"]
    lead = _plain_reason(reasons[0], language)

    if language == "es":
        body = f"Yo pasaría de esta. La gestión de riesgo la rechazó de plano: {lead}."
        for extra_reason in reasons[1:]:
            body += f" {_plain_reason(extra_reason, 'es').capitalize()}."
        body += (
            " Como un RECHAZO siempre implica un veto irrevocable en el resto del "
            "proceso, los agentes analíticos no tienen una opinión aparte aquí — la "
            "decisión de riesgo es final y esta nota no la cuestiona."
        )
        return body

    body = f"I'd pass on this one. Risk management rejected it outright: {lead}."
    for extra_reason in reasons[1:]:
        body += f" {_plain_reason(extra_reason, 'en').capitalize()}."
    body += (
        " Because a REJECT always carries a hard veto through the rest of the "
        "process, the analytical agents don't get a separate say here — risk's "
        "call is final and this note doesn't second-guess it."
    )
    return body


def _reduce_paragraph(risk_decision: dict, language: Language) -> str:
    lead = _plain_reason(risk_decision["reasons"][0], language)
    sizing = risk_decision["sizingAdjustment"]
    if language == "es":
        return (
            f"La gestión de riesgo no la mató, pero la recortó: el tamaño se redujo "
            f"a {sizing:.0%} de lo solicitado. Motivo: {lead}."
        )
    return (
        f"Risk management didn't kill this one, but trimmed it: size was cut to "
        f"{sizing:.0%} of what was requested. Reason: {lead}."
    )


def _approve_paragraph(risk_decision: dict, language: Language) -> str:
    reasons = risk_decision["reasons"]
    if language == "es":
        if reasons and reasons[0]["code"] != "OK":
            return (
                f"La gestión de riesgo la aprobó al tamaño completo solicitado. "
                f"{_plain_reason(reasons[0], 'es')}."
            )
        return (
            "La gestión de riesgo la aprobó al tamaño completo solicitado. "
            "Ningún límite se activó."
        )

    if reasons and reasons[0]["code"] != "OK":
        reason_text = _plain_reason(reasons[0], "en")
        return f"Risk management cleared this at full requested size. {reason_text}."
    return "Risk management cleared this at full requested size. No limits were binding."


def _council_summary_sentence(
    thesis: ChiefIntelligenceThesis, opinions: list[AgentOpinion], language: Language
) -> str:
    support_n = sum(1 for o in opinions if o.stance == "SUPPORT")
    oppose_n = sum(1 for o in opinions if o.stance == "OPPOSE")
    neutral_n = sum(1 for o in opinions if o.stance == "NEUTRAL")

    if language == "es":
        neutral_word = "neutral" if neutral_n == 1 else "neutrales"
        return (
            f"Los agentes del consejo respondieron {support_n} a favor, {oppose_n} "
            f"en contra, {neutral_n} {neutral_word} (lectura final: "
            f"{_stance_es(thesis.final_stance)})."
        )
    return (
        f"The council's agents came back {support_n} in support, {oppose_n} "
        f"opposed, {neutral_n} neutral (final read: {thesis.final_stance})."
    )


def _disagreement_paragraph(
    thesis: ChiefIntelligenceThesis, opinions: list[AgentOpinion], language: Language
) -> str:
    dissenting: list[str] = []
    for opinion in opinions:
        if opinion.stance != "OPPOSE":
            continue
        for finding in opinion.findings:
            reason = {"code": finding.code, "detail": finding.detail}
            dissenting.append(_plain_reason(reason, language))
            if len(dissenting) >= 2:
                break
        if len(dissenting) >= 2:
            break

    if language == "es":
        findings_text = (
            "; ".join(dissenting) if dissenting else "no se marcaron hallazgos específicos"
        )
        return (
            f"Dicho esto, esto no es una lectura del todo limpia puertas adentro: los "
            f"agentes analíticos están {_stance_es(thesis.final_stance).lower()} "
            f"respecto a esto (puntaje ponderado {thesis.weighted_score:+.2f}), "
            f"aunque la gestión de riesgo aprobó el tamaño. Específicamente: "
            f"{findings_text}. Vale la pena tomar esa brecha como motivo de "
            f"precaución extra, no como razón para anular la decisión de riesgo en "
            f"ningún sentido — las dos verificaciones responden preguntas distintas "
            f"(si esto está permitido vs. si esto luce bien construido). "
            f"{_council_summary_sentence(thesis, opinions, 'es')}"
        )

    findings_text = "; ".join(dissenting) if dissenting else "no specific findings were flagged"
    return (
        f"That said, this isn't a clean read internally: the analytical agents are "
        f"{thesis.final_stance.lower()} on it (weighted score {thesis.weighted_score:+.2f}), "
        f"even though risk management approved the size. Specifically: {findings_text}. "
        f"Worth treating that gap as a reason for extra caution, not a reason to "
        f"override risk's decision either way — the two checks answer different "
        f"questions (is this allowed vs. does this look well-formed). "
        f"{_council_summary_sentence(thesis, opinions, 'en')}"
    )


def generate_narrative(
    symbol: str,
    regime: RegimeResult,
    candidate: dict | None,
    risk_decision: dict | None,
    opinions: list[AgentOpinion],
    thesis: ChiefIntelligenceThesis | None,
    *,
    candidate_pool_size: int = 1,
    language: Language = "en",
) -> str:
    """Renders a broker-voice explanation of an already-made decision.

    `candidate=None` means no strategy was cleared to run in the current
    regime (`strategy_engine.run_strategies` returned `[]`) — the only
    caller-decided fact this function trusts without a paired decision.
    Whenever a candidate is given, `risk_decision` and `thesis` must be
    given too (the caller has already run the real pipeline); this raises
    rather than silently guessing at a decision that was never made.

    `language` only changes prose — see the module docstring for what
    stays untranslated (reason/finding `detail` strings) and what's
    translated for display only (regime/direction/stance words inside
    Spanish sentences, via the `_..._LABELS_ES` tables).
    """
    if candidate is None:
        return f"{_no_candidate_paragraph(symbol, regime, language)}\n\n{_disclaimer(language)}"

    if risk_decision is None or thesis is None:
        raise ValueError("risk_decision and thesis are required whenever a candidate is given")

    paragraphs: list[str] = []
    if candidate_pool_size > 1:
        paragraphs.append(_multi_candidate_paragraph(candidate, candidate_pool_size, language))

    paragraphs.append(_opening_paragraph(symbol, regime, candidate, language))
    plan_sentence = _entry_stop_target_sentence(candidate, language)
    edge_sentence = _edge_cost_sentence(candidate, language)
    paragraphs.append(f"{plan_sentence} {edge_sentence}")

    decision = risk_decision["decision"]
    if decision == "REJECT":
        paragraphs.append(_reject_paragraph(risk_decision, language))
    elif decision == "REDUCE":
        paragraphs.append(_reduce_paragraph(risk_decision, language))
        paragraphs.append(_council_summary_sentence(thesis, opinions, language))
    elif decision == "APPROVE":
        paragraphs.append(_approve_paragraph(risk_decision, language))
        if thesis.final_stance == "SUPPORT":
            paragraphs.append(_council_summary_sentence(thesis, opinions, language))
        else:
            paragraphs.append(_disagreement_paragraph(thesis, opinions, language))
    else:
        raise ValueError(f"unrecognized risk decision {decision!r}")

    paragraphs.append(_disclaimer(language))
    return "\n\n".join(paragraphs)
