"""Deterministic, rule-based narrative generation over the pipeline's own
structured output (a `StrategyCandidate` dict, a `RegimeResult`, a
`risk_engine.evaluate()` decision dict, the council's `AgentOpinion`s and
`ChiefIntelligenceThesis`).

This module runs strictly *after* `risk_engine.evaluate()` and
`council.synthesize()` have already produced their outputs — it restates
them in plain-language, broker-voice prose. It never re-derives a decision
(the same discipline `RiskOfficer` already follows: its opinion *is*
`risk_engine`'s decision, translated, never recomputed), never invents a
number that isn't already a field on its inputs, and never generates text
via an LLM — every sentence here is a fixed template over real data.

Per brief Section 24 ("do not treat AI text output as a market signal")
and this repo's non-goal of never promising profitability: every branch
below ends with `DISCLAIMER`, verbatim, including the REJECT branch. This
is presentation of an existing decision, not a new source of trading
authority — nothing in this module can place, size, or approve a trade.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from regime_engine.classify import RegimeResult

    from ai_council.council import ChiefIntelligenceThesis
    from ai_council.opinion import AgentOpinion

DISCLAIMER = (
    "This note is generated by rule-based code, not a licensed financial advisor, "
    "and reflects a simulated paper-trading account (starting equity $100,000, "
    "placeholder risk limits) — not your real portfolio. It is for informational "
    "and educational purposes only, is not investment advice, and no real capital "
    "is at risk from anything described here. Nothing in this note places or "
    "authorizes a trade."
)

# Every code below is verified against risk_engine.engine and the four
# ai_council agents' actual source (grepped, not guessed). A code that
# isn't in this table still gets a readable fallback (see _plain_reason) —
# this table is polish, the fallback is the actual safety net.
_CODE_PHRASES: dict[str, str] = {
    "OK": "no limits were binding",
    "KILL_SWITCH_ENGAGED": "the global kill switch is engaged",
    "CIRCUIT_BREAKER_ENGAGED": "a circuit breaker is engaged",
    "STALE_DATA": "the market data feeding this is stale",
    "LIQUIDITY_SPREAD_LIMIT": "the spread is wider than the allowed limit",
    "MAX_DAILY_LOSS": "the day's loss limit is already breached",
    "MAX_WEEKLY_LOSS": "the week's loss limit is already breached",
    "MAX_PORTFOLIO_DRAWDOWN": "portfolio drawdown is past its limit",
    "MAX_PORTFOLIO_VAR": "portfolio value-at-risk is past its limit",
    "MAX_POSITION": "the position size limit for this asset",
    "MAX_ASSET_EXPOSURE": "the asset exposure limit",
    "MAX_GROSS_EXPOSURE": "the gross exposure limit",
    "MAX_LEVERAGE": "the leverage limit",
    "MAX_NET_EXPOSURE": "the net exposure limit",
    "RISK_PER_TRADE_LIMIT": "the size requested risks more than the per-trade budget",
    "EDGE_TO_COST_RATIO": "the edge-to-cost math",
    "EDGE_DOES_NOT_COVER_COSTS": "the edge doesn't clear costs by enough",
    "INVALID_COST_BASIS": "the cost basis on this candidate doesn't check out",
    "LOW_REGIME_CONFIDENCE": "the regime read itself isn't very confident",
    "WEAK_SIGNAL_STRENGTH": "the signal strength is weak",
    "THIN_EDGE_MARGIN": "the edge over costs looks thin",
    "LOW_HISTORICAL_WIN_RATE": "the historical win rate on this setup is low",
    "REGIME_MISMATCH": "this candidate was built against a regime that's since changed",
    "MISSING_STRATEGY_ID": "the candidate is missing its strategy identifier",
    "INCONSISTENT_STOP_TARGET_ORDERING": (
        "the stop/target prices aren't ordered correctly for the stated direction"
    ),
}


def _confidence_word(confidence: float) -> str:
    """Fixed, deterministic bucket — not per-call color commentary."""
    if confidence >= 0.75:
        return "reasonably"
    if confidence >= 0.5:
        return "moderately"
    return "only mildly"


def _plain_reason(reason: dict) -> str:
    prefix = _CODE_PHRASES.get(reason["code"], reason["code"].replace("_", " ").lower())
    return f"{prefix} ({reason['detail']})"


def _no_candidate_paragraph(symbol: str, regime: RegimeResult) -> str:
    return (
        f"{symbol} is currently in a {regime.label} regime (classifier confidence "
        f"{regime.confidence:.0%}). None of the three strategies this platform runs "
        f"today — trend-following, mean-reversion, or breakout — are cleared to "
        f"operate in this regime, so no trade candidate was generated. That's not a "
        f"signal to do nothing forever; it just means this specific rule set has "
        f"nothing to say about {symbol} right now."
    )


def _multi_candidate_paragraph(candidate: dict, pool_size: int) -> str:
    return (
        f"{pool_size} strategies generated candidates for {candidate['symbol']} in "
        f"this {candidate['regime']} regime; this note covers {candidate['strategyId']} "
        f"(direction {candidate['direction']}), selected because it had the highest "
        f"expected edge ({candidate['expectedEdge']:.4f}) among them. The others are "
        f"not discussed here."
    )


def _opening_paragraph(symbol: str, regime: RegimeResult, candidate: dict) -> str:
    return (
        f"{symbol} is reading as a {regime.label} regime right now, and the "
        f"classifier is {_confidence_word(regime.confidence)} confident in that read "
        f"({regime.confidence:.0%}). On the back of that, the {candidate['strategyId']} "
        f"strategy put together a {candidate['direction']} idea on a "
        f"{candidate['horizon']} horizon."
    )


def _entry_stop_target_sentence(candidate: dict) -> str:
    parts = []
    entry_price = candidate["entryLogic"].get("entryPrice")
    if entry_price is not None:
        parts.append(f"entry around {entry_price}")
    stop_price = candidate["stopLogic"].get("stopPrice")
    if stop_price is not None:
        parts.append(f"a stop at {stop_price}")
    target_price = candidate["targetLogic"].get("targetPrice")
    if target_price is not None:
        parts.append(f"a target at {target_price}")
    if not parts:
        return "The strategy didn't populate explicit entry/stop/target prices for this candidate."
    return "The plan as generated: " + ", ".join(parts) + "."


def _edge_cost_sentence(candidate: dict) -> str:
    return (
        f"Expected edge is modeled at {candidate['expectedEdge']:.4f} against "
        f"estimated costs of {candidate['estimatedCosts']:.4f} — these are the "
        f"strategy's own placeholder estimates, not a validated profit forecast."
    )


def _reject_paragraph(risk_decision: dict) -> str:
    reasons = risk_decision["reasons"]
    lead = _plain_reason(reasons[0])
    body = f"I'd pass on this one. Risk management rejected it outright: {lead}."
    for extra_reason in reasons[1:]:
        body += f" {_plain_reason(extra_reason).capitalize()}."
    body += (
        " Because a REJECT always carries a hard veto through the rest of the "
        "process, the analytical agents don't get a separate say here — risk's "
        "call is final and this note doesn't second-guess it."
    )
    return body


def _reduce_paragraph(risk_decision: dict) -> str:
    lead = _plain_reason(risk_decision["reasons"][0])
    sizing = risk_decision["sizingAdjustment"]
    return (
        f"Risk management didn't kill this one, but trimmed it: size was cut to "
        f"{sizing:.0%} of what was requested. Reason: {lead}."
    )


def _approve_paragraph(risk_decision: dict) -> str:
    reasons = risk_decision["reasons"]
    if reasons and reasons[0]["code"] != "OK":
        return f"Risk management cleared this at full requested size. {_plain_reason(reasons[0])}."
    return "Risk management cleared this at full requested size. No limits were binding."


def _council_summary_sentence(thesis: ChiefIntelligenceThesis, opinions: list[AgentOpinion]) -> str:
    support_n = sum(1 for o in opinions if o.stance == "SUPPORT")
    oppose_n = sum(1 for o in opinions if o.stance == "OPPOSE")
    neutral_n = sum(1 for o in opinions if o.stance == "NEUTRAL")
    return (
        f"The council's agents came back {support_n} in support, {oppose_n} "
        f"opposed, {neutral_n} neutral (final read: {thesis.final_stance})."
    )


def _disagreement_paragraph(thesis: ChiefIntelligenceThesis, opinions: list[AgentOpinion]) -> str:
    dissenting: list[str] = []
    for opinion in opinions:
        if opinion.stance != "OPPOSE":
            continue
        for finding in opinion.findings:
            dissenting.append(_plain_reason({"code": finding.code, "detail": finding.detail}))
            if len(dissenting) >= 2:
                break
        if len(dissenting) >= 2:
            break
    findings_text = "; ".join(dissenting) if dissenting else "no specific findings were flagged"

    return (
        f"That said, this isn't a clean read internally: the analytical agents are "
        f"{thesis.final_stance.lower()} on it (weighted score {thesis.weighted_score:+.2f}), "
        f"even though risk management approved the size. Specifically: {findings_text}. "
        f"Worth treating that gap as a reason for extra caution, not a reason to "
        f"override risk's decision either way — the two checks answer different "
        f"questions (is this allowed vs. does this look well-formed). "
        f"{_council_summary_sentence(thesis, opinions)}"
    )


def generate_narrative(
    symbol: str,
    regime: RegimeResult,
    candidate: dict | None,
    risk_decision: dict | None,
    opinions: list[AgentOpinion],
    thesis: ChiefIntelligenceThesis | None,
    *,
    candidate_pool_size: int = 1,
) -> str:
    """Renders a broker-voice explanation of an already-made decision.

    `candidate=None` means no strategy was cleared to run in the current
    regime (`strategy_engine.run_strategies` returned `[]`) — the only
    caller-decided fact this function trusts without a paired decision.
    Whenever a candidate is given, `risk_decision` and `thesis` must be
    given too (the caller has already run the real pipeline); this raises
    rather than silently guessing at a decision that was never made.
    """
    if candidate is None:
        return f"{_no_candidate_paragraph(symbol, regime)}\n\n{DISCLAIMER}"

    if risk_decision is None or thesis is None:
        raise ValueError("risk_decision and thesis are required whenever a candidate is given")

    paragraphs: list[str] = []
    if candidate_pool_size > 1:
        paragraphs.append(_multi_candidate_paragraph(candidate, candidate_pool_size))

    paragraphs.append(_opening_paragraph(symbol, regime, candidate))
    paragraphs.append(f"{_entry_stop_target_sentence(candidate)} {_edge_cost_sentence(candidate)}")

    decision = risk_decision["decision"]
    if decision == "REJECT":
        paragraphs.append(_reject_paragraph(risk_decision))
    elif decision == "REDUCE":
        paragraphs.append(_reduce_paragraph(risk_decision))
        paragraphs.append(_council_summary_sentence(thesis, opinions))
    elif decision == "APPROVE":
        paragraphs.append(_approve_paragraph(risk_decision))
        if thesis.final_stance == "SUPPORT":
            paragraphs.append(_council_summary_sentence(thesis, opinions))
        else:
            paragraphs.append(_disagreement_paragraph(thesis, opinions))
    else:
        raise ValueError(f"unrecognized risk decision {decision!r}")

    paragraphs.append(DISCLAIMER)
    return "\n\n".join(paragraphs)
